### ISSUE TITLE
@comunica/query-sparql-link-traversal-solid is broken (in node script, browser and cli)

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica-feature-solid#46]
#### Issue type:

- :bug: Bug 

____
#### Description:

____
#### Crash log:

It errors with the following output
```
/home/jesse/Documents/github/comunica-test-link-traversal/node_modules/@comunica/actor-query-result-serialize-stats/lib/ActionObserverHttp.js:17
        this.httpInvalidator.addInvalidateListener(() => {
                             ^
TypeError: Cannot read properties of undefined (reading 'addInvalidateListener')
    at new ActionObserverHttp (/home/jesse/Documents/github/comunica-test-link-traversal/node_modules/@comunica/actor-query-result-serialize-stats/lib/ActionObserverHttp.js:17:30)
    at Object.<anonymous> (/home/jesse/Documents/github/comunica-test-link-traversal/node_modules/@comunica/query-sparql-link-traversal-solid/engine-default.js:315:209)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/home/jesse/.nvm/versions/node/v16.17.0/lib/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jesse/Documents/github/comunica-test-link-traversal/node_modules/@comunica/query-sparql-link-traversal-solid/lib/QueryEngine.js:5:23)

jesse@ranchmorty:~/Documents/github/comunica-test-link-traversal$ node --version
v16.17.0
jesse@ranchmorty:~/Documents/github/comunica-test-link-traversal$ npm --version
8.15.0
```

**Comment by rubensworks** [comment]
What version are you using? From npm or GH?

**Comment by jeswr** [comment]
From npm using 0.0.2-alpha.2.0

**Comment by jeswr** [comment]
Ah ty - you might also want to make sure that it has the `latest` tag rather than the `next` tag (which is why I had 0.0.2-alpha.2.0 installed)

**Comment by jeswr** [comment]
Working now on `@next` tag - so this can be closed (prefereably after updating the tag as well)

**Comment by rubensworks** [comment]
Best to keep using `@next` for now, as this is all still experimental. Once we have something stable enough, we can update the `latest` tag.
